"""edit guest table

Revision ID: 10fddc7fed02
Revises: d370351f3305
Create Date: 2023-02-22 14:29:29.334851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10fddc7fed02'
down_revision = 'd370351f3305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_guest_firstname')
        batch_op.drop_index('ix_guest_lastname')
        batch_op.create_index(batch_op.f('ix_guest_name'), ['name'], unique=False)
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_guest_name'))
        batch_op.create_index('ix_guest_lastname', ['lastname'], unique=False)
        batch_op.create_index('ix_guest_firstname', ['firstname'], unique=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
