"""guest table update

Revision ID: 2121ed28566c
Revises: 712f1a29c452
Create Date: 2023-02-22 18:45:18.652885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2121ed28566c'
down_revision = '712f1a29c452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rsvp', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_guest_rsvp'), ['rsvp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guest_rsvp'))
        batch_op.drop_column('rsvp')

    # ### end Alembic commands ###
