"""user table update

Revision ID: 656849addbcf
Revises: 1cde9e8b40dc
Create Date: 2023-02-22 19:04:18.214785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656849addbcf'
down_revision = '1cde9e8b40dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.drop_index('ix_guest_name')
        batch_op.create_index(batch_op.f('ix_guest_name'), ['name'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_name')
        batch_op.create_index(batch_op.f('ix_user_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_name'))
        batch_op.create_index('ix_user_name', ['name'], unique=False)

    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guest_name'))
        batch_op.create_index('ix_guest_name', ['name'], unique=False)

    # ### end Alembic commands ###
