"""user table update

Revision ID: 712f1a29c452
Revises: 10fddc7fed02
Create Date: 2023-02-22 18:42:01.921342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712f1a29c452'
down_revision = '10fddc7fed02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('section', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('rsvp', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_rsvp'), ['rsvp'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_section'), ['section'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_section'))
        batch_op.drop_index(batch_op.f('ix_user_rsvp'))
        batch_op.drop_index(batch_op.f('ix_user_name'))
        batch_op.drop_column('rsvp')
        batch_op.drop_column('section')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
