"""users table

Revision ID: b6fbe78d4090
Revises: 6745f805e273
Create Date: 2023-02-28 15:44:28.714391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6fbe78d4090'
down_revision = '6745f805e273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_avatar'), ['avatar'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_avatar'))
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
