"""guest tableupdate

Revision ID: d370351f3305
Revises: 5d6ebe78fdd9
Create Date: 2023-02-21 22:24:47.486335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd370351f3305'
down_revision = '5d6ebe78fdd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_guest_registered'), ['registered'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guest_registered'))
        batch_op.drop_column('registered')

    # ### end Alembic commands ###
