"""Guest users table

Revision ID: dd0add91eba5
Revises: 26d9a6ce825f
Create Date: 2023-02-21 18:22:12.342846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd0add91eba5'
down_revision = '26d9a6ce825f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('section', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guest_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_guest_firstname'), ['firstname'], unique=False)
        batch_op.create_index(batch_op.f('ix_guest_lastname'), ['lastname'], unique=False)
        batch_op.create_index(batch_op.f('ix_guest_section'), ['section'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_firstname')
        batch_op.drop_index('ix_user_inguestlist')
        batch_op.drop_index('ix_user_lastname')
        batch_op.drop_index('ix_user_section')
        batch_op.drop_column('lastname')
        batch_op.drop_column('section')
        batch_op.drop_column('firstname')
        batch_op.drop_column('inguestlist')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inguestlist', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('firstname', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('section', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_index('ix_user_section', ['section'], unique=False)
        batch_op.create_index('ix_user_lastname', ['lastname'], unique=False)
        batch_op.create_index('ix_user_inguestlist', ['inguestlist'], unique=False)
        batch_op.create_index('ix_user_firstname', ['firstname'], unique=False)

    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guest_section'))
        batch_op.drop_index(batch_op.f('ix_guest_lastname'))
        batch_op.drop_index(batch_op.f('ix_guest_firstname'))
        batch_op.drop_index(batch_op.f('ix_guest_email'))

    op.drop_table('guest')
    # ### end Alembic commands ###
