"""verified account

Revision ID: f2cca8ea7174
Revises: 453a95b908da
Create Date: 2023-03-05 19:54:00.806035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2cca8ea7174'
down_revision = '453a95b908da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_verified'), ['verified'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_verified'))
        batch_op.drop_column('verified')

    # ### end Alembic commands ###
